package com.isoft.airinfo.db.mapper;

import java.util.List;

import com.isoft.airinfo.db.entity.CommonUser;

public interface CommonUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_user
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_user
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    int insert(CommonUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_user
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    int insertSelective(CommonUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_user
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    CommonUser selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_user
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    int updateByPrimaryKeySelective(CommonUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_user
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    int updateByPrimaryKey(CommonUser record);
    List<CommonUser> findAll();

}