package com.isoft.airinfo.db.mapper;

import java.util.List;


import com.isoft.airinfo.db.entity.Consumption;

public interface ConsumptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    int insert(Consumption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    int insertSelective(Consumption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    Consumption selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    int updateByPrimaryKeySelective(Consumption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    int updateByPrimaryKey(Consumption record);
    List<Consumption> findAll();
    
    int deleteUserByUserIds(List<String> userIds);
}