package com.isoft.airinfo.db.mapper;

import java.util.List;


import com.isoft.airinfo.db.entity.Score;
import com.isoft.airinfo.db.entity.rank;

public interface ScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    int insert(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    int insertSelective(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    Score selectByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    int updateByPrimaryKeySelective(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    int updateByPrimaryKey(Score record);
    List<Score> findAll();
    List<Score> findRank();
    List<rank> findRank1();
    int deleteUserByUserIds(List<String> userIds);
}