package com.isoft.airinfo.db.entity;

public class CommonUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_user.uid
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_user.uname
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_user.upassword
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    private String upassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_user.uid
     *
     * @return the value of common_user.uid
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_user.uid
     *
     * @param uid the value for common_user.uid
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_user.uname
     *
     * @return the value of common_user.uname
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_user.uname
     *
     * @param uname the value for common_user.uname
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    public void setUname(String uname) {
        this.uname = uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_user.upassword
     *
     * @return the value of common_user.upassword
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    public String getUpassword() {
        return upassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_user.upassword
     *
     * @param upassword the value for common_user.upassword
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    public void setUpassword(String upassword) {
        this.upassword = upassword;
    }
}