package com.isoft.airinfo.db.entity;

import java.util.Date;

public class userAndConsumption {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumption.cid
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    private Integer cid;
    private String uname;
    public String getUname() {
		return uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumption.ctime
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumption.cnumber
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    private Integer cnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumption.uid
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumption.cid
     *
     * @return the value of consumption.cid
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumption.cid
     *
     * @param cid the value for consumption.cid
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumption.ctime
     *
     * @return the value of consumption.ctime
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumption.ctime
     *
     * @param ctime the value for consumption.ctime
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumption.cnumber
     *
     * @return the value of consumption.cnumber
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    public Integer getCnumber() {
        return cnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumption.cnumber
     *
     * @param cnumber the value for consumption.cnumber
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    public void setCnumber(Integer cnumber) {
        this.cnumber = cnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumption.uid
     *
     * @return the value of consumption.uid
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumption.uid
     *
     * @param uid the value for consumption.uid
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}