package com.isoft.airinfo.db.entity;

import java.util.Date;

public class userAndScore {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.sid
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    private Integer sid;

    public String getUname() {
		return uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	private String uname;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.stime
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    private Date stime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.snumber
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    private Integer snumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.uid
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.sid
     *
     * @return the value of score.sid
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.sid
     *
     * @param sid the value for score.sid
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.stime
     *
     * @return the value of score.stime
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    public Date getStime() {
        return stime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.stime
     *
     * @param stime the value for score.stime
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    public void setStime(Date stime) {
        this.stime = stime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.snumber
     *
     * @return the value of score.snumber
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    public Integer getSnumber() {
        return snumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.snumber
     *
     * @param snumber the value for score.snumber
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    public void setSnumber(Integer snumber) {
        this.snumber = snumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.uid
     *
     * @return the value of score.uid
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.uid
     *
     * @param uid the value for score.uid
     *
     * @mbg.generated Thu May 24 22:57:51 CST 2018
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}